services:
  nexus:
    image: sonatype/nexus3:3.86.2
    container_name: nexus
    ports:
      - "12345:8081"
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data: {} # This line creates a named volume
#admin
#86a5b5b3-cc36-4968-95b4-0f85b9ba224b